#!/bin/sh
# This file is part of TagSoup.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.  You may also distribute
# and/or modify it under version 1.2 of the Academic Free License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
# 
# 
# Compile all Java code
./compile-enums elements >HTMLModels.i
./compile-elements elements >HTMLSchema.i
./compile-attributes attributes >>HTMLSchema.i
./compile-entities entities >>HTMLSchema.i
./compile-statetable statetable >HTMLScanner.i
