#!/usr/bin/perl -w
# This file is part of TagSoup.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.  You may also distribute
# and/or modify it under version 1.2 of the Academic Free License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
# 
# 
# Generate attributes for HTMLSchema.i

use strict;

my %elems = ();

$_ = <>;
while (<>) {
	chomp;
	my ($elem, $attr, $dort) = split(/\t/);
	$elems{$elem} = 1 unless $elem eq "~ALL";
	my ($type, $default) = ("CDATA", "null");
	if ($dort eq "ID" || $dort eq "IDREF" ||
			 $dort eq "IDREFS" || $dort eq "NMTOKEN") {
		$type = $dort;
		}
	else {
		$default = '"' . $dort . '"';
		}
	if ($elem eq "~ALL") {
		foreach $elem (sort(keys(%elems))) {
			print "\t\tattribute(\"$elem\", \"$attr\", \"$type\", $default);\n";
			}
		}
	else {
		print "\t\tattribute(\"$elem\", \"$attr\", \"$type\", $default);\n";
		}
	}

print "\n";
