#!/usr/bin/perl -w
# This file is part of TagSoup.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.  You may also distribute
# and/or modify it under version 1.2 of the Academic Free License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
# 
# 
# Generate enums for HTMLModels.i

use strict;

my %modnums;

sub modelize {
	my ($models) = @_;
	$models = uc($models);
	$models =~ s/[#%]//g;
	my @models = split(/\+/, $models);
	for my $model (@models) {
		$modnums{$model} = 1 unless $model eq "EMPTY";
		}
	}

$_ = <>;
while (<>) {
	chomp;
	my (undef, undef, $contains, $belongs, undef, undef) = split(/\t/);
	modelize($contains);
	modelize($belongs);
	}

my $modnum = 0;
foreach my $modname (sort (keys %modnums)) {
	$modnum++;
	print "\tpublic static final int M_$modname = 1 << $modnum;\n";
	}
