// This file is part of TagSoup.
// 
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.  You may also distribute
// and/or modify it under version 1.2 of the Academic Free License.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
// 
// 
/**
This class provides a Schema that has been preinitialized with HTML
elements, attributes, and character entity declarations.  All the declarations
normally provided with HTML 4.01 are given, plus some that are IE-specific
and NS4-specific.  Attribute declarations of type CDATA with no default
value are not included.
*/

package org.ccil.cowan.tagsoup;
public class HTMLSchema extends Schema implements HTMLModels {

	private static HTMLSchema theSchema = new HTMLSchema();


	/**
	Returns a newly constructed HTMLSchema object independent of
	any existing ones.
	*/

	public HTMLSchema() {
		// Start of Schema calls
		elementType("<pcdata>", M_EMPTY, M_PCDATA, 0);
		elementType("<root>", M_HTMLEL, M_EMPTY, 0);
		elementType("a", M_PCDATA|M_INLINE, M_INLINE, 0);
		elementType("abbr", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("acronym", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("address", M_PCDATA|M_INLINE|M_P, M_BLOCK, 0);
		elementType("applet", M_PARAM|M_PCDATA|M_INLINE|M_BLOCK, M_INLINE, 0);
		elementType("area", M_EMPTY, M_AREA, 0);
		elementType("b", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("base", M_EMPTY, M_HEAD, 0);
		elementType("basefont", M_EMPTY, M_INLINE, 0);
		elementType("bdo", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("big", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("blockquote", M_PCDATA|M_INLINE|M_BLOCK, M_BLOCK, 0);
		elementType("body", M_PCDATA|M_INLINE|M_BLOCK|M_INSDEL, M_HTML|M_BODY, 0);
		elementType("br", M_EMPTY, M_INLINE, 0);
		elementType("button", M_INLINE|M_BLOCK, M_INLINE, 0);
		elementType("caption", M_PCDATA|M_INLINE, M_TABLE, 0);
		elementType("center", M_PCDATA|M_INLINE|M_BLOCK, M_BLOCK, 0);
		elementType("cite", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("code", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("col", M_EMPTY, M_COL|M_TABLE, 0);
		elementType("colgroup", M_COL, M_TABLE, 0);
		elementType("dd", M_PCDATA|M_INLINE|M_BLOCK, M_DEF, 0);
		elementType("del", M_PCDATA|M_INLINE|M_BLOCK, M_INSDEL, F_RESTART);
		elementType("dfn", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("dir", M_LI, M_BLOCK, 0);
		elementType("div", M_PCDATA|M_INLINE|M_BLOCK, M_BLOCK, 0);
		elementType("dl", M_DEF, M_BLOCK, 0);
		elementType("dt", M_PCDATA|M_INLINE, M_DEF, 0);
		elementType("em", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("fieldset", M_PCDATA|M_LEGEND|M_INLINE|M_BLOCK, M_BLOCK, 0);
		elementType("font", M_PCDATA|M_INLINE, M_INLINE, 0);
		elementType("form", M_PCDATA|M_INLINE|M_BLOCK, M_BLOCK, 0);
		elementType("frame", M_EMPTY, M_FRAME, 0);
		elementType("frameset", M_FRAME, M_FRAME|M_HTML, 0);
		elementType("h1", M_PCDATA|M_INLINE, M_BLOCK, 0);
		elementType("h2", M_PCDATA|M_INLINE, M_BLOCK, 0);
		elementType("h3", M_PCDATA|M_INLINE, M_BLOCK, 0);
		elementType("h4", M_PCDATA|M_INLINE, M_BLOCK, 0);
		elementType("h5", M_PCDATA|M_INLINE, M_BLOCK, 0);
		elementType("h6", M_PCDATA|M_INLINE, M_BLOCK, 0);
		elementType("head", M_HEAD, M_HTML, 0);
		elementType("hr", M_EMPTY, M_BLOCK, 0);
		elementType("html", M_HTML|M_HTMLEL, M_HTMLEL, 0);
		elementType("i", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("iframe", M_PCDATA|M_INLINE|M_BLOCK, M_INLINE, 0);
		elementType("img", M_EMPTY, M_INLINE, 0);
		elementType("input", M_EMPTY, M_INLINE, 0);
		elementType("ins", M_PCDATA|M_INLINE|M_BLOCK, M_INSDEL, F_RESTART);
		elementType("isindex", M_EMPTY, M_HEAD, 0);
		elementType("kbd", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("label", M_PCDATA|M_INLINE, M_INLINE, 0);
		elementType("legend", M_PCDATA|M_INLINE, M_LEGEND, 0);
		elementType("li", M_PCDATA|M_INLINE|M_BLOCK, M_LI, 0);
		elementType("link", M_EMPTY, M_HEAD, 0);
		elementType("map", M_BLOCK|M_AREA, M_INLINE, 0);
		elementType("menu", M_LI, M_BLOCK, 0);
		elementType("meta", M_EMPTY, M_HEAD, 0);
		elementType("noframes", M_BODY, M_BLOCK|M_HTML|M_FRAME, 0);
		elementType("noscript", M_PCDATA|M_INLINE|M_BLOCK, M_BLOCK, 0);
		elementType("object", M_PARAM|M_PCDATA|M_INLINE|M_BLOCK, M_HEAD|M_INLINE, 0);
		elementType("ol", M_LI, M_BLOCK, 0);
		elementType("optgroup", M_OPTIONS, M_OPTIONS, 0);
		elementType("option", M_PCDATA, M_OPTION|M_OPTIONS, 0);
		elementType("p", M_PCDATA|M_INLINE, M_BLOCK|M_P, 0);
		elementType("param", M_EMPTY, M_PARAM, 0);
		elementType("pre", M_PCDATA|M_INLINE, M_BLOCK, 0);
		elementType("q", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("s", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("samp", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("script", M_PCDATA, M_HEAD|M_INLINE, F_CDATA);
		elementType("select", M_OPTIONS, M_INLINE, 0);
		elementType("small", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("span", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("strike", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("strong", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("style", M_PCDATA, M_HEAD, F_CDATA);
		elementType("sub", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("sup", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("table", M_TABLE, M_BLOCK, 0);
		elementType("tbody", M_TR, M_TABLE, 0);
		elementType("td", M_PCDATA|M_INLINE|M_BLOCK, M_CELL, 0);
		elementType("textarea", M_PCDATA, M_INLINE, 0);
		elementType("tfoot", M_TR, M_TABLE, 0);
		elementType("th", M_PCDATA|M_INLINE|M_BLOCK, M_CELL, 0);
		elementType("thead", M_TR, M_TABLE, 0);
		elementType("title", M_PCDATA, M_HEAD, 0);
		elementType("tr", M_CELL, M_TR, 0);
		elementType("tt", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("u", M_PCDATA|M_INLINE, M_INLINE, F_RESTART);
		elementType("ul", M_LI, M_BLOCK, 0);
		elementType("var", M_PCDATA|M_INLINE, M_INLINE, 0);

		parent("<pcdata>", "body");
		parent("a", "body");
		parent("abbr", "body");
		parent("acronym", "body");
		parent("address", "body");
		parent("applet", "body");
		parent("area", "map");
		parent("b", "body");
		parent("base", "head");
		parent("basefont", "body");
		parent("bdo", "body");
		parent("big", "body");
		parent("blockquote", "body");
		parent("body", "html");
		parent("br", "body");
		parent("button", "form");
		parent("caption", "body");
		parent("center", "body");
		parent("cite", "body");
		parent("code", "body");
		parent("col", "table");
		parent("colgroup", "table");
		parent("dd", "dl");
		parent("del", "body");
		parent("dfn", "body");
		parent("dir", "body");
		parent("div", "body");
		parent("dl", "body");
		parent("dt", "dl");
		parent("em", "body");
		parent("fieldset", "form");
		parent("font", "body");
		parent("form", "body");
		parent("frame", "body");
		parent("frameset", "html");
		parent("h1", "body");
		parent("h2", "body");
		parent("h3", "body");
		parent("h4", "body");
		parent("h5", "body");
		parent("h6", "body");
		parent("head", "html");
		parent("hr", "body");
		parent("html", "<root>");
		parent("i", "body");
		parent("iframe", "body");
		parent("img", "body");
		parent("input", "form");
		parent("ins", "body");
		parent("isindex", "head");
		parent("kbd", "body");
		parent("label", "form");
		parent("legend", "fieldset");
		parent("li", "ul");
		parent("link", "head");
		parent("map", "body");
		parent("menu", "body");
		parent("meta", "head");
		parent("noframes", "html");
		parent("noscript", "body");
		parent("object", "body");
		parent("ol", "body");
		parent("optgroup", "form");
		parent("option", "optgroup");
		parent("p", "body");
		parent("param", "body");
		parent("pre", "body");
		parent("q", "body");
		parent("s", "body");
		parent("samp", "body");
		parent("script", "head");
		parent("select", "form");
		parent("small", "body");
		parent("span", "body");
		parent("strike", "body");
		parent("strong", "body");
		parent("style", "head");
		parent("sub", "body");
		parent("sup", "body");
		parent("table", "body");
		parent("tbody", "table");
		parent("td", "tr");
		parent("textarea", "form");
		parent("tfoot", "table");
		parent("th", "tr");
		parent("thead", "table");
		parent("title", "head");
		parent("tr", "tbody");
		parent("tt", "body");
		parent("u", "body");
		parent("ul", "body");
		parent("var", "body");

		attribute("a", "hreflang", "NMTOKEN", null);
		attribute("a", "shape", "CDATA", "rect");
		attribute("a", "tabindex", "NMTOKEN", null);
		attribute("applet", "align", "NMTOKEN", null);
		attribute("area", "nohref", "NMTOKEN", null);
		attribute("area", "shape", "CDATA", "rect");
		attribute("area", "tabindex", "NMTOKEN", null);
		attribute("bdo", "dir", "NMTOKEN", null);
		attribute("br", "clear", "CDATA", "none");
		attribute("button", "disabled", "NMTOKEN", null);
		attribute("button", "tabindex", "NMTOKEN", null);
		attribute("button", "type", "CDATA", "submit");
		attribute("caption", "align", "NMTOKEN", null);
		attribute("col", "align", "NMTOKEN", null);
		attribute("col", "span", "CDATA", "1");
		attribute("col", "valign", "NMTOKEN", null);
		attribute("colgroup", "align", "NMTOKEN", null);
		attribute("colgroup", "span", "CDATA", "1");
		attribute("colgroup", "valign", "NMTOKEN", null);
		attribute("dir", "compact", "NMTOKEN", null);
		attribute("div", "align", "NMTOKEN", null);
		attribute("dl", "compact", "NMTOKEN", null);
		attribute("form", "enctype", "CDATA", "application/x-www-form-urlencoded");
		attribute("form", "method", "CDATA", "get");
		attribute("frame", "frameborder", "CDATA", "1");
		attribute("frame", "noresize", "NMTOKEN", null);
		attribute("frame", "scrolling", "CDATA", "auto");
		attribute("h1", "align", "NMTOKEN", null);
		attribute("h2", "align", "NMTOKEN", null);
		attribute("h3", "align", "NMTOKEN", null);
		attribute("h4", "align", "NMTOKEN", null);
		attribute("h5", "align", "NMTOKEN", null);
		attribute("h6", "align", "NMTOKEN", null);
		attribute("hr", "align", "NMTOKEN", null);
		attribute("hr", "noshade", "NMTOKEN", null);
		attribute("html", "version", "CDATA", "-//W3C//DTD HTML 4.01 Transitional//EN");
		attribute("iframe", "align", "NMTOKEN", null);
		attribute("iframe", "frameborder", "CDATA", "1");
		attribute("iframe", "scrolling", "CDATA", "auto");
		attribute("img", "align", "NMTOKEN", null);
		attribute("img", "ismap", "NMTOKEN", null);
		attribute("input", "align", "NMTOKEN", null);
		attribute("input", "checked", "NMTOKEN", null);
		attribute("input", "disabled", "NMTOKEN", null);
		attribute("input", "ismap", "NMTOKEN", null);
		attribute("input", "maxlength", "NMTOKEN", null);
		attribute("input", "readonly", "NMTOKEN", null);
		attribute("input", "tabindex", "NMTOKEN", null);
		attribute("input", "type", "CDATA", "text");
		attribute("label", "for", "IDREF", null);
		attribute("legend", "align", "NMTOKEN", null);
		attribute("li", "value", "NMTOKEN", null);
		attribute("link", "hreflang", "NMTOKEN", null);
		attribute("menu", "compact", "NMTOKEN", null);
		attribute("meta", "http-equiv", "NMTOKEN", null);
		attribute("meta", "name", "NMTOKEN", null);
		attribute("object", "align", "NMTOKEN", null);
		attribute("object", "declare", "NMTOKEN", null);
		attribute("object", "tabindex", "NMTOKEN", null);
		attribute("ol", "compact", "NMTOKEN", null);
		attribute("ol", "start", "NMTOKEN", null);
		attribute("optgroup", "disabled", "NMTOKEN", null);
		attribute("option", "disabled", "NMTOKEN", null);
		attribute("option", "selected", "NMTOKEN", null);
		attribute("p", "align", "NMTOKEN", null);
		attribute("param", "valuetype", "CDATA", "data");
		attribute("pre", "width", "NMTOKEN", null);
		attribute("script", "defer", "NMTOKEN", null);
		attribute("select", "disabled", "NMTOKEN", null);
		attribute("select", "multiple", "NMTOKEN", null);
		attribute("select", "size", "NMTOKEN", null);
		attribute("select", "tabindex", "NMTOKEN", null);
		attribute("table", "align", "NMTOKEN", null);
		attribute("table", "frame", "NMTOKEN", null);
		attribute("table", "rules", "NMTOKEN", null);
		attribute("tbody", "align", "NMTOKEN", null);
		attribute("tbody", "valign", "NMTOKEN", null);
		attribute("td", "align", "NMTOKEN", null);
		attribute("td", "colspan", "CDATA", "1");
		attribute("td", "headers", "IDREFS", null);
		attribute("td", "nowrap", "NMTOKEN", null);
		attribute("td", "rowspan", "CDATA", "1");
		attribute("td", "scope", "NMTOKEN", null);
		attribute("td", "valign", "NMTOKEN", null);
		attribute("textarea", "cols", "NMTOKEN", null);
		attribute("textarea", "disabled", "NMTOKEN", null);
		attribute("textarea", "readonly", "NMTOKEN", null);
		attribute("textarea", "rows", "NMTOKEN", null);
		attribute("textarea", "tabindex", "NMTOKEN", null);
		attribute("tfoot", "align", "NMTOKEN", null);
		attribute("tfoot", "valign", "NMTOKEN", null);
		attribute("th", "align", "NMTOKEN", null);
		attribute("th", "colspan", "CDATA", "1");
		attribute("th", "headers", "IDREFS", null);
		attribute("th", "nowrap", "NMTOKEN", null);
		attribute("th", "rowspan", "CDATA", "1");
		attribute("th", "scope", "NMTOKEN", null);
		attribute("th", "valign", "NMTOKEN", null);
		attribute("thead", "align", "NMTOKEN", null);
		attribute("thead", "valign", "NMTOKEN", null);
		attribute("tr", "align", "NMTOKEN", null);
		attribute("tr", "valign", "NMTOKEN", null);
		attribute("ul", "compact", "NMTOKEN", null);
		attribute("ul", "type", "NMTOKEN", null);
		attribute("a", "class", "NMTOKEN", null);
		attribute("applet", "class", "NMTOKEN", null);
		attribute("area", "class", "NMTOKEN", null);
		attribute("bdo", "class", "NMTOKEN", null);
		attribute("br", "class", "NMTOKEN", null);
		attribute("button", "class", "NMTOKEN", null);
		attribute("caption", "class", "NMTOKEN", null);
		attribute("col", "class", "NMTOKEN", null);
		attribute("colgroup", "class", "NMTOKEN", null);
		attribute("dir", "class", "NMTOKEN", null);
		attribute("div", "class", "NMTOKEN", null);
		attribute("dl", "class", "NMTOKEN", null);
		attribute("form", "class", "NMTOKEN", null);
		attribute("frame", "class", "NMTOKEN", null);
		attribute("h1", "class", "NMTOKEN", null);
		attribute("h2", "class", "NMTOKEN", null);
		attribute("h3", "class", "NMTOKEN", null);
		attribute("h4", "class", "NMTOKEN", null);
		attribute("h5", "class", "NMTOKEN", null);
		attribute("h6", "class", "NMTOKEN", null);
		attribute("hr", "class", "NMTOKEN", null);
		attribute("html", "class", "NMTOKEN", null);
		attribute("iframe", "class", "NMTOKEN", null);
		attribute("img", "class", "NMTOKEN", null);
		attribute("input", "class", "NMTOKEN", null);
		attribute("label", "class", "NMTOKEN", null);
		attribute("legend", "class", "NMTOKEN", null);
		attribute("li", "class", "NMTOKEN", null);
		attribute("link", "class", "NMTOKEN", null);
		attribute("menu", "class", "NMTOKEN", null);
		attribute("meta", "class", "NMTOKEN", null);
		attribute("object", "class", "NMTOKEN", null);
		attribute("ol", "class", "NMTOKEN", null);
		attribute("optgroup", "class", "NMTOKEN", null);
		attribute("option", "class", "NMTOKEN", null);
		attribute("p", "class", "NMTOKEN", null);
		attribute("param", "class", "NMTOKEN", null);
		attribute("pre", "class", "NMTOKEN", null);
		attribute("script", "class", "NMTOKEN", null);
		attribute("select", "class", "NMTOKEN", null);
		attribute("table", "class", "NMTOKEN", null);
		attribute("tbody", "class", "NMTOKEN", null);
		attribute("td", "class", "NMTOKEN", null);
		attribute("textarea", "class", "NMTOKEN", null);
		attribute("tfoot", "class", "NMTOKEN", null);
		attribute("th", "class", "NMTOKEN", null);
		attribute("thead", "class", "NMTOKEN", null);
		attribute("tr", "class", "NMTOKEN", null);
		attribute("ul", "class", "NMTOKEN", null);
		attribute("a", "dir", "NMTOKEN", null);
		attribute("applet", "dir", "NMTOKEN", null);
		attribute("area", "dir", "NMTOKEN", null);
		attribute("bdo", "dir", "NMTOKEN", null);
		attribute("br", "dir", "NMTOKEN", null);
		attribute("button", "dir", "NMTOKEN", null);
		attribute("caption", "dir", "NMTOKEN", null);
		attribute("col", "dir", "NMTOKEN", null);
		attribute("colgroup", "dir", "NMTOKEN", null);
		attribute("dir", "dir", "NMTOKEN", null);
		attribute("div", "dir", "NMTOKEN", null);
		attribute("dl", "dir", "NMTOKEN", null);
		attribute("form", "dir", "NMTOKEN", null);
		attribute("frame", "dir", "NMTOKEN", null);
		attribute("h1", "dir", "NMTOKEN", null);
		attribute("h2", "dir", "NMTOKEN", null);
		attribute("h3", "dir", "NMTOKEN", null);
		attribute("h4", "dir", "NMTOKEN", null);
		attribute("h5", "dir", "NMTOKEN", null);
		attribute("h6", "dir", "NMTOKEN", null);
		attribute("hr", "dir", "NMTOKEN", null);
		attribute("html", "dir", "NMTOKEN", null);
		attribute("iframe", "dir", "NMTOKEN", null);
		attribute("img", "dir", "NMTOKEN", null);
		attribute("input", "dir", "NMTOKEN", null);
		attribute("label", "dir", "NMTOKEN", null);
		attribute("legend", "dir", "NMTOKEN", null);
		attribute("li", "dir", "NMTOKEN", null);
		attribute("link", "dir", "NMTOKEN", null);
		attribute("menu", "dir", "NMTOKEN", null);
		attribute("meta", "dir", "NMTOKEN", null);
		attribute("object", "dir", "NMTOKEN", null);
		attribute("ol", "dir", "NMTOKEN", null);
		attribute("optgroup", "dir", "NMTOKEN", null);
		attribute("option", "dir", "NMTOKEN", null);
		attribute("p", "dir", "NMTOKEN", null);
		attribute("param", "dir", "NMTOKEN", null);
		attribute("pre", "dir", "NMTOKEN", null);
		attribute("script", "dir", "NMTOKEN", null);
		attribute("select", "dir", "NMTOKEN", null);
		attribute("table", "dir", "NMTOKEN", null);
		attribute("tbody", "dir", "NMTOKEN", null);
		attribute("td", "dir", "NMTOKEN", null);
		attribute("textarea", "dir", "NMTOKEN", null);
		attribute("tfoot", "dir", "NMTOKEN", null);
		attribute("th", "dir", "NMTOKEN", null);
		attribute("thead", "dir", "NMTOKEN", null);
		attribute("tr", "dir", "NMTOKEN", null);
		attribute("ul", "dir", "NMTOKEN", null);
		attribute("a", "id", "ID", null);
		attribute("applet", "id", "ID", null);
		attribute("area", "id", "ID", null);
		attribute("bdo", "id", "ID", null);
		attribute("br", "id", "ID", null);
		attribute("button", "id", "ID", null);
		attribute("caption", "id", "ID", null);
		attribute("col", "id", "ID", null);
		attribute("colgroup", "id", "ID", null);
		attribute("dir", "id", "ID", null);
		attribute("div", "id", "ID", null);
		attribute("dl", "id", "ID", null);
		attribute("form", "id", "ID", null);
		attribute("frame", "id", "ID", null);
		attribute("h1", "id", "ID", null);
		attribute("h2", "id", "ID", null);
		attribute("h3", "id", "ID", null);
		attribute("h4", "id", "ID", null);
		attribute("h5", "id", "ID", null);
		attribute("h6", "id", "ID", null);
		attribute("hr", "id", "ID", null);
		attribute("html", "id", "ID", null);
		attribute("iframe", "id", "ID", null);
		attribute("img", "id", "ID", null);
		attribute("input", "id", "ID", null);
		attribute("label", "id", "ID", null);
		attribute("legend", "id", "ID", null);
		attribute("li", "id", "ID", null);
		attribute("link", "id", "ID", null);
		attribute("menu", "id", "ID", null);
		attribute("meta", "id", "ID", null);
		attribute("object", "id", "ID", null);
		attribute("ol", "id", "ID", null);
		attribute("optgroup", "id", "ID", null);
		attribute("option", "id", "ID", null);
		attribute("p", "id", "ID", null);
		attribute("param", "id", "ID", null);
		attribute("pre", "id", "ID", null);
		attribute("script", "id", "ID", null);
		attribute("select", "id", "ID", null);
		attribute("table", "id", "ID", null);
		attribute("tbody", "id", "ID", null);
		attribute("td", "id", "ID", null);
		attribute("textarea", "id", "ID", null);
		attribute("tfoot", "id", "ID", null);
		attribute("th", "id", "ID", null);
		attribute("thead", "id", "ID", null);
		attribute("tr", "id", "ID", null);
		attribute("ul", "id", "ID", null);
		attribute("a", "lang", "NMTOKEN", null);
		attribute("applet", "lang", "NMTOKEN", null);
		attribute("area", "lang", "NMTOKEN", null);
		attribute("bdo", "lang", "NMTOKEN", null);
		attribute("br", "lang", "NMTOKEN", null);
		attribute("button", "lang", "NMTOKEN", null);
		attribute("caption", "lang", "NMTOKEN", null);
		attribute("col", "lang", "NMTOKEN", null);
		attribute("colgroup", "lang", "NMTOKEN", null);
		attribute("dir", "lang", "NMTOKEN", null);
		attribute("div", "lang", "NMTOKEN", null);
		attribute("dl", "lang", "NMTOKEN", null);
		attribute("form", "lang", "NMTOKEN", null);
		attribute("frame", "lang", "NMTOKEN", null);
		attribute("h1", "lang", "NMTOKEN", null);
		attribute("h2", "lang", "NMTOKEN", null);
		attribute("h3", "lang", "NMTOKEN", null);
		attribute("h4", "lang", "NMTOKEN", null);
		attribute("h5", "lang", "NMTOKEN", null);
		attribute("h6", "lang", "NMTOKEN", null);
		attribute("hr", "lang", "NMTOKEN", null);
		attribute("html", "lang", "NMTOKEN", null);
		attribute("iframe", "lang", "NMTOKEN", null);
		attribute("img", "lang", "NMTOKEN", null);
		attribute("input", "lang", "NMTOKEN", null);
		attribute("label", "lang", "NMTOKEN", null);
		attribute("legend", "lang", "NMTOKEN", null);
		attribute("li", "lang", "NMTOKEN", null);
		attribute("link", "lang", "NMTOKEN", null);
		attribute("menu", "lang", "NMTOKEN", null);
		attribute("meta", "lang", "NMTOKEN", null);
		attribute("object", "lang", "NMTOKEN", null);
		attribute("ol", "lang", "NMTOKEN", null);
		attribute("optgroup", "lang", "NMTOKEN", null);
		attribute("option", "lang", "NMTOKEN", null);
		attribute("p", "lang", "NMTOKEN", null);
		attribute("param", "lang", "NMTOKEN", null);
		attribute("pre", "lang", "NMTOKEN", null);
		attribute("script", "lang", "NMTOKEN", null);
		attribute("select", "lang", "NMTOKEN", null);
		attribute("table", "lang", "NMTOKEN", null);
		attribute("tbody", "lang", "NMTOKEN", null);
		attribute("td", "lang", "NMTOKEN", null);
		attribute("textarea", "lang", "NMTOKEN", null);
		attribute("tfoot", "lang", "NMTOKEN", null);
		attribute("th", "lang", "NMTOKEN", null);
		attribute("thead", "lang", "NMTOKEN", null);
		attribute("tr", "lang", "NMTOKEN", null);
		attribute("ul", "lang", "NMTOKEN", null);

		entity("&AElig", '\u00C6');
		entity("&Aacute", '\u00C1');
		entity("&Acirc", '\u00C2');
		entity("&Agrave", '\u00C0');
		entity("&Alpha", '\u0391');
		entity("&Aring", '\u00C5');
		entity("&Atilde", '\u00C3');
		entity("&Auml", '\u00C4');
		entity("&Beta", '\u0392');
		entity("&Ccedil", '\u00C7');
		entity("&Chi", '\u03A7');
		entity("&Dagger", '\u2021');
		entity("&Delta", '\u0394');
		entity("&ETH", '\u00D0');
		entity("&Eacute", '\u00C9');
		entity("&Ecirc", '\u00CA');
		entity("&Egrave", '\u00C8');
		entity("&Epsilon", '\u0395');
		entity("&Eta", '\u0397');
		entity("&Euml", '\u00CB');
		entity("&Gamma", '\u0393');
		entity("&Iacute", '\u00CD');
		entity("&Icirc", '\u00CE');
		entity("&Igrave", '\u00CC');
		entity("&Iota", '\u0399');
		entity("&Iuml", '\u00CF');
		entity("&Kappa", '\u039A');
		entity("&Lambda", '\u039B');
		entity("&Mu", '\u039C');
		entity("&Ntilde", '\u00D1');
		entity("&Nu", '\u039D');
		entity("&OElig", '\u0152');
		entity("&Oacute", '\u00D3');
		entity("&Ocirc", '\u00D4');
		entity("&Ograve", '\u00D2');
		entity("&Omega", '\u03A9');
		entity("&Omicron", '\u039F');
		entity("&Oslash", '\u00D8');
		entity("&Otilde", '\u00D5');
		entity("&Ouml", '\u00D6');
		entity("&Phi", '\u03A6');
		entity("&Pi", '\u03A0');
		entity("&Prime", '\u2033');
		entity("&Psi", '\u03A8');
		entity("&Rho", '\u03A1');
		entity("&Scaron", '\u0160');
		entity("&Sigma", '\u03A3');
		entity("&THORN", '\u00DE');
		entity("&Tau", '\u03A4');
		entity("&Theta", '\u0398');
		entity("&Uacute", '\u00DA');
		entity("&Ucirc", '\u00DB');
		entity("&Ugrave", '\u00D9');
		entity("&Upsilon", '\u03A5');
		entity("&Uuml", '\u00DC');
		entity("&Xi", '\u039E');
		entity("&Yacute", '\u00DD');
		entity("&Yuml", '\u0178');
		entity("&Zeta", '\u0396');
		entity("&aacute", '\u00E1');
		entity("&acirc", '\u00E2');
		entity("&acute", '\u00B4');
		entity("&aelig", '\u00E6');
		entity("&agrave", '\u00E0');
		entity("&alefsym", '\u2135');
		entity("&alpha", '\u03B1');
		entity("&amp", '\u0026');
		entity("&and", '\u2227');
		entity("&ang", '\u2220');
		entity("&aring", '\u00E5');
		entity("&asymp", '\u2248');
		entity("&atilde", '\u00E3');
		entity("&auml", '\u00E4');
		entity("&bdquo", '\u201E');
		entity("&beta", '\u03B2');
		entity("&brvbar", '\u00A6');
		entity("&bull", '\u2022');
		entity("&cap", '\u2229');
		entity("&ccedil", '\u00E7');
		entity("&cedil", '\u00B8');
		entity("&cent", '\u00A2');
		entity("&chi", '\u03C7');
		entity("&circ", '\u02C6');
		entity("&clubs", '\u2663');
		entity("&cong", '\u2245');
		entity("&copy", '\u00A9');
		entity("&crarr", '\u21B5');
		entity("&cup", '\u222A');
		entity("&curren", '\u00A4');
		entity("&dArr", '\u21D3');
		entity("&dagger", '\u2020');
		entity("&darr", '\u2193');
		entity("&deg", '\u00B0');
		entity("&delta", '\u03B4');
		entity("&diams", '\u2666');
		entity("&divide", '\u00F7');
		entity("&eacute", '\u00E9');
		entity("&ecirc", '\u00EA');
		entity("&egrave", '\u00E8');
		entity("&empty", '\u2205');
		entity("&emsp", '\u2003');
		entity("&ensp", '\u2002');
		entity("&epsilon", '\u03B5');
		entity("&equiv", '\u2261');
		entity("&eta", '\u03B7');
		entity("&eth", '\u00F0');
		entity("&euml", '\u00EB');
		entity("&euro", '\u20AC');
		entity("&exist", '\u2203');
		entity("&fnof", '\u0192');
		entity("&forall", '\u2200');
		entity("&frac12", '\u00BD');
		entity("&frac14", '\u00BC');
		entity("&frac34", '\u00BE');
		entity("&frasl", '\u2044');
		entity("&gamma", '\u03B3');
		entity("&ge", '\u2265');
		entity("&gt", '\u003E');
		entity("&hArr", '\u21D4');
		entity("&harr", '\u2194');
		entity("&hearts", '\u2665');
		entity("&hellip", '\u2026');
		entity("&iacute", '\u00ED');
		entity("&icirc", '\u00EE');
		entity("&iexcl", '\u00A1');
		entity("&igrave", '\u00EC');
		entity("&image", '\u2111');
		entity("&infin", '\u221E');
		entity("&int", '\u222B');
		entity("&iota", '\u03B9');
		entity("&iquest", '\u00BF');
		entity("&isin", '\u2208');
		entity("&iuml", '\u00EF');
		entity("&kappa", '\u03BA');
		entity("&lArr", '\u21D0');
		entity("&lambda", '\u03BB');
		entity("&lang", '\u2329');
		entity("&laquo", '\u00AB');
		entity("&larr", '\u2190');
		entity("&lceil", '\u2308');
		entity("&ldquo", '\u201C');
		entity("&le", '\u2264');
		entity("&lfloor", '\u230A');
		entity("&lowast", '\u2217');
		entity("&loz", '\u25CA');
		entity("&lrm", '\u200E');
		entity("&lsaquo", '\u2039');
		entity("&lsquo", '\u2018');
		entity("&lt", '\u003C');
		entity("&macr", '\u00AF');
		entity("&mdash", '\u2014');
		entity("&micro", '\u00B5');
		entity("&middot", '\u00B7');
		entity("&minus", '\u2212');
		entity("&mu", '\u03BC');
		entity("&nabla", '\u2207');
		entity("&nbsp", '\u00A0');
		entity("&ndash", '\u2013');
		entity("&ne", '\u2260');
		entity("&ni", '\u220B');
		entity("&not", '\u00AC');
		entity("&notin", '\u2209');
		entity("&nsub", '\u2284');
		entity("&ntilde", '\u00F1');
		entity("&nu", '\u03BD');
		entity("&oacute", '\u00F3');
		entity("&ocirc", '\u00F4');
		entity("&oelig", '\u0153');
		entity("&ograve", '\u00F2');
		entity("&oline", '\u203E');
		entity("&omega", '\u03C9');
		entity("&omicron", '\u03BF');
		entity("&oplus", '\u2295');
		entity("&or", '\u2228');
		entity("&ordf", '\u00AA');
		entity("&ordm", '\u00BA');
		entity("&oslash", '\u00F8');
		entity("&otilde", '\u00F5');
		entity("&otimes", '\u2297');
		entity("&ouml", '\u00F6');
		entity("&para", '\u00B6');
		entity("&part", '\u2202');
		entity("&permil", '\u2030');
		entity("&perp", '\u22A5');
		entity("&phi", '\u03C6');
		entity("&pi", '\u03C0');
		entity("&piv", '\u03D6');
		entity("&plusmn", '\u00B1');
		entity("&pound", '\u00A3');
		entity("&prime", '\u2032');
		entity("&prod", '\u220F');
		entity("&prop", '\u221D');
		entity("&psi", '\u03C8');
		entity("&quot", '\u0022');
		entity("&rArr", '\u21D2');
		entity("&radic", '\u221A');
		entity("&rang", '\u232A');
		entity("&raquo", '\u00BB');
		entity("&rarr", '\u2192');
		entity("&rceil", '\u2309');
		entity("&rdquo", '\u201D');
		entity("&real", '\u211C');
		entity("&reg", '\u00AE');
		entity("&rfloor", '\u230B');
		entity("&rho", '\u03C1');
		entity("&rlm", '\u200F');
		entity("&rsaquo", '\u203A');
		entity("&rsquo", '\u2019');
		entity("&sbquo", '\u201A');
		entity("&scaron", '\u0161');
		entity("&sdot", '\u22C5');
		entity("&sect", '\u00A7');
		entity("&shy", '\u00AD');
		entity("&sigma", '\u03C3');
		entity("&sigmaf", '\u03C2');
		entity("&sim", '\u223C');
		entity("&spades", '\u2660');
		entity("&sub", '\u2282');
		entity("&sube", '\u2286');
		entity("&sum", '\u2211');
		entity("&sup", '\u2283');
		entity("&sup1", '\u00B9');
		entity("&sup2", '\u00B2');
		entity("&sup3", '\u00B3');
		entity("&supe", '\u2287');
		entity("&szlig", '\u00DF');
		entity("&tau", '\u03C4');
		entity("&there4", '\u2234');
		entity("&theta", '\u03B8');
		entity("&thetasym", '\u03D1');
		entity("&thinsp", '\u2009');
		entity("&thorn", '\u00FE');
		entity("&tilde", '\u02DC');
		entity("&times", '\u00D7');
		entity("&trade", '\u2122');
		entity("&uArr", '\u21D1');
		entity("&uacute", '\u00FA');
		entity("&uarr", '\u2191');
		entity("&ucirc", '\u00FB');
		entity("&ugrave", '\u00F9');
		entity("&uml", '\u00A8');
		entity("&upsih", '\u03D2');
		entity("&upsilon", '\u03C5');
		entity("&uuml", '\u00FC');
		entity("&weierp", '\u2118');
		entity("&xi", '\u03BE');
		entity("&yacute", '\u00FD');
		entity("&yen", '\u00A5');
		entity("&yuml", '\u00FF');
		entity("&zeta", '\u03B6');
		entity("&zwj", '\u200D');
		entity("&zwnj", '\u200C');

		// End of Schema calls
		}

	/**
	Returns the shared HTMLSchema object.  This object is initialized
	when the HTMLSchema class is loaded.  The parser uses this schema
	by default.  Any declarations that are automatically or manually
	added to it will be shared with every (default) parser.  To avoid
	this, use the HTMLSchema constructor instead.
	*/

	public static HTMLSchema sharedSchema() {
		return theSchema;
		}

	/**
	Return the HTML namespace name.
	*/

	public String getURI() {
		return "http://www.w3.org/1999/xhtml";
		}

	/**
	Return the HTML prefix.
	*/

	public String getPrefix() {
		return "html";
		}


	}
